namespace: "membership-tracker"

replicaCount: 2

image:
  repository: 798742520104.dkr.ecr.us-west-1.amazonaws.com/hlab-ecr-repo
  pullPolicy: Always
  digest: "sha256:dummydigest0000000000000000000000000000000000000000000000000000000000" #  Replace with digest dynamically fetched ##Checkov fix
  # tag: "devbld"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: memTrkPy.home.lab
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []