apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      automountServiceAccountToken: false ## Added to disable automounting of service account token per SonarCloud recommendation
      terminationGracePeriodSeconds: 30 #  Ensures safe pod shutdown
      containers:
      - name: membershipTracker-py-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        securityContext:
          readOnlyRootFilesystem: true # Prevents write access to the root filesystem
          runAsUser: 1000 # Use a non-root user
          runAsNonRoot: true # Prevents running as root
          allowPrivilegeEscalation: false # Prevents security vulnerabilities
        ports:
        - containerPort: 8000
        ## Resource Limits added as per SonarCloud recommendation
        resources:  
          requests:
            memory: "256Mi" # 256 MB
            cpu: "250m" # 250 millicpu
            ephemeral-storage: "1Gi" # 1 GB
          limits:
            memory: "512Mi" # 512 MB
            cpu: "500m" # 500 millicpu
        env:
        - name: APP_VERSION
          value: "{{ .Chart.AppVersion }}" #  Dynamically updated from the GitHub Actions
      affinity:
        podAntiAffinity:  #  Ensures that pods are not scheduled on the same node
          requiredDuringSchedulingIgnoredDuringExecution:  #  Ensures that pods are not scheduled on the same node
            - labelSelector: #  Ensures that pods are not scheduled on the same node
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - membershipTracker-py-web
              topologyKey: "kubernetes.io/hostname"