Version: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }} ##Checkov fix
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: {{ .Chart.Name }}